name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure DevOps pipeline
        uses: Azure/pipeline-templates/trigger-azure-pipelines@main
        with:
          org: YourOrgName
          project: YourProjectName
          pipeline: 'YourPipelineName'
          branch: main
          token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
