name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure DevOps pipeline
        uses: Azure/pipeline-templates/trigger-azure-pipelines@main
        with:
          org: umshaikh
          project: DevOps Task 2
          pipeline: 'UmairAhmed000.DevOpsAST_Task_2(3)'
          branch: main
          token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
