trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build_and_deploy
  displayName: 'Build and deploy ASP.Net Core app to Azure Web App - DevOpstask2'
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Setup .NET Core'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: |
      dotnet build --configuration Release
    displayName: 'Build with dotnet'

  - script: |
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/myapp
    displayName: 'Dotnet publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Upload artifact for deployment job'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/myapp'
      ArtifactName: 'dotnet-app'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
      ArtifactName: 'publish'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure Web App'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'c870b16a-0d82-4c1d-a664-f8c74ca20960'  # Azure service connection name
      appType: 'webApp'
      WebAppName: 'DevOpstask2'  # Name of your Azure Web App
      packageForLinux: '$(Build.ArtifactStagingDirectory)/publish'
      enableCustomDeployment: true
