name: Build and deploy ASP.Net Core app to Azure Web App - DevOpstask2

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub Actions workflow steps
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: $(Build.ArtifactStagingDirectory)/myapp

      # Azure DevOps deployment steps
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(build.sourcesDirectory)'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DevOpstask2'
          slot-name: 'Production'
          package: '$(Build.ArtifactStagingDirectory)/myapp'

      # Optionally, you can add cleanup steps if necessary
